// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mNob6KrVWE1Pp5dxU1irRo5nnSgiEnQ',
    appId: '1:139679978119:web:d37d89c1e53acca8071e22',
    messagingSenderId: '139679978119',
    projectId: 'my-finance-19941',
    authDomain: 'my-finance-19941.firebaseapp.com',
    storageBucket: 'my-finance-19941.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxKBkjqax2S02dxoTRKKudmpzGDTZ6x88',
    appId: '1:139679978119:android:ac3e5fd2d8bb983f071e22',
    messagingSenderId: '139679978119',
    projectId: 'my-finance-19941',
    storageBucket: 'my-finance-19941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV3luRG5GnbnyffuYFRmScz9QkbHqrJvs',
    appId: '1:139679978119:ios:407fcd9fc500a66a071e22',
    messagingSenderId: '139679978119',
    projectId: 'my-finance-19941',
    storageBucket: 'my-finance-19941.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV3luRG5GnbnyffuYFRmScz9QkbHqrJvs',
    appId: '1:139679978119:ios:407fcd9fc500a66a071e22',
    messagingSenderId: '139679978119',
    projectId: 'my-finance-19941',
    storageBucket: 'my-finance-19941.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8mNob6KrVWE1Pp5dxU1irRo5nnSgiEnQ',
    appId: '1:139679978119:web:9b866d931a792ebd071e22',
    messagingSenderId: '139679978119',
    projectId: 'my-finance-19941',
    authDomain: 'my-finance-19941.firebaseapp.com',
    storageBucket: 'my-finance-19941.firebasestorage.app',
  );
}
